ALTER TABLE users
    ADD COLUMN email VARCHAR(100) NOT NULL,
    ADD COLUMN phone VARCHAR(30),
    MODIFY COLUMN ime VARCHAR(50) NOT NULL,
    MODIFY COLUMN prezime VARCHAR(50) NOT NULL,
    ADD UNIQUE (email);
